version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./laravel-project:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./laravel-project/public/index.php:/var/www/public/index.php
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:5.7.38
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  frontend:
    build:
      context: ./docker/frontend/
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'npm run dev'
    ports:
      - "3000:3000"

    #build：「一つのDockerを詳細に組み立てる＝Dockerfileを作る」ための命令
    #context：docker buildコマンドを実行した場所
    #context: .：コンテキストをルートディレクトリに設定
    #volumes：自分のパソコンの中のファイルを、Dockerの環境に接続する命令
    #environment：環境変数

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
