name: Test Frontend and Backend

on: [push, pull_request]

jobs:
  frontend-tests:
    name: Run Node.js Frontend Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: "20.3.1"

      - name: Install Dependencies and Run Tests
        run: |
          cd ${{ github.workspace }}/frontend
          npm ci
          npm run test
