name: CI flow for Amazon ECS

on: [push]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.3.1"

      - name: Install Dependencies and Run tests
        run: |
          cd ${{ github.workspace }}/FOQS/frontend
          npm install
          npm run test
